package org.swetlokognatsk.earking_out.core.domain.model.music.sounds;

import java.io.Serializable;
import java.util.HashSet;
import java.util.Set;
import static java.util.Objects.requireNonNull;
import org.swetlokognatsk.earking_out.core.domain.model.base.ValueObject;
import org.swetlokognatsk.earking_out.core.domain.model.music.Accidentals;
import org.swetlokognatsk.earking_out.core.domain.model.music.NoteNames;
import org.swetlokognatsk.earking_out.core.domain.model.music.Octaves;
import org.swetlokognatsk.earking_out.core.domain.model.piano.key.PianoKeyNumber;
import org.swetlokognatsk.earking_out.core.domain.services.domain.music.NotesNormalizingService;
import org.swetlokognatsk.earking_out.core.ports.di.DI;
import lombok.Data;

/**
 * `pianoKeyNumber <-> note` is one<-to->one-or-two relationship
 */
@Data
public final class Note extends ValueObject implements Serializable {
    private static final long serialVersionUID = 1L;
    private static Set<Note> innerStorage;

    public final NoteNames noteName;
    public final Accidentals accidental;
    public final Octaves octave;

    static {
        var innerStorage = new HashSet<Note>();

        for (var noteName : NoteNames.values()) {
            for (var accidental : Accidentals.values()) {
                for (var octave : Octaves.values()) {
                    innerStorage.add(new Note(noteName, accidental, octave));
                }
            }
        }
        removeOneKeyAsideBorderNotes(innerStorage);

        Note.innerStorage = innerStorage;
    }

    // these notes were generated by `for-for-for` loop, but they do not exist in app's domain
    private static void removeOneKeyAsideBorderNotes(final Set<Note> notes) {
        notes.remove(new Note(NoteNames.C, Accidentals.FLAT, Octaves.FIRST));
        notes.remove(new Note(NoteNames.B, Accidentals.SHARP, Octaves.SEVENTH));
    }

    private Note(final NoteNames noteName, final Accidentals accidental, final Octaves octave) {
        this.noteName = requireNonNull(noteName);
        this.accidental = accidental;
        this.octave = requireNonNull(octave);
    }

    public static Note valueOf(final NoteNames noteName, final Accidentals accidental, final Octaves octave) {
        // yep, pretty not optimized, but we know that premature optimization is bad idea
        return innerStorage.stream()
                .filter((Note note) -> note.noteName.equals(noteName)
                        && note.accidental.equals(accidental)
                        && note.octave.equals(octave))
                .findFirst()
                .orElseThrow();
    }

    public static Note[] denormalize(final PianoKeyNumber pianoKeyNumber) {
        return innerStorage.stream()
                .filter((Note note) -> note.normalize()
                        .equals(pianoKeyNumber))
                .toArray(Note[]::new);
    }

    public static Note[] getAll() {
        return innerStorage.toArray(Note[]::new);
    }

    // technically, low-level-module-depends-on-high-level-module violation. pragmatically, convenience method
    public PianoKeyNumber normalize() {
        return DI.get(NotesNormalizingService.class)
                .normalize(this);
    }

    public Note withOctave(Octaves octave) {
        return valueOf(noteName, accidental, octave);
    }

    public Note withAccidental(Accidentals accidental) {
        return valueOf(noteName, accidental, octave);
    }
}
