debug=true
spring.main.log-startup-info=true
logging.level.*=DEBUG

spring.main.lazy-initialization=false

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# TODO edit on prod for web
spring.datasource.url=jdbc:sqlite:earking_out.db
spring.datasource.driver-class-name=org.sqlite.JDBC