spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
spring.datasource.url=jdbc:sqlite:earking_out.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.docker.compose.enabled=false