debug=true
spring.main.log-startup-info=true
logging.level.*=DEBUG

spring.main.lazy-initialization=false

spring.jpa.database-platform=org.hibernate.community.dialect.SQLiteDialect
# TODO edit on prod for web
spring.datasource.url=jdbc:sqlite:earking_out.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.docker.compose.file=./src/main/java/org/swetlokognatsk/earking_out/app/web/compose.dev.yaml
spring.docker.compose.stop.command=down

spring.devtools.restart.quiet-period=1500ms
spring.devtools.restart.poll-interval=2000ms

server.port=250