spring.docker.compose.enabled=true
spring.docker.compose.file=./src/main/java/org/swetlokognatsk/earking_out/app/web/compose.dev.yaml
spring.docker.compose.stop.command=down

spring.devtools.restart.quiet-period=1500ms
spring.devtools.restart.poll-interval=2000ms